name: Bug / Problem Report
description: Report a problem or bug with the Minecraft server setup
title: "[BUG] "
labels: [bug]
body:
  - type: input
    id: description
    attributes:
      label: Bug Description
      placeholder: "Describe the problem you encountered..."
    validations:
      required: true
  - type: dropdown
    id: server_type
    attributes:
      label: Server Type
      options:
        - Vanilla
        - Forge
        - Fabric
        - Spigot
        - Paper
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - Darwin (macOS)
        - Linux
  - type: dropdown
    id: architecture
    attributes:
      label: Architecture
      options:
        - x86_64 (64-bit / AMD)
        - arm64 (Apple Silicon / ARM)
  - type: input
    id: minecraft_version
    attributes:
      label: Minecraft Version
      placeholder: "e.g. 1.21.3"
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: "List the steps to reproduce the bug..."
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: "What did you expect to happen?"
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: "What actually happened?"
